### ISSUE TITLE
BTL module?

### ISSUE THREAD

**Issue by slrslr** [ctminime/QB_Migrate_to_Linux#1]
Hello, in Python 3.8 & Arch Linux, anyone knows how to install BTL module that [the script seems to request](https://forum.manjaro.org/t/manjaro-python-3-8-5-btl-module-install-modulenotfounderror-no-module-named-btl/32610)?

**Comment by slrslr** [comment]
I have installed $ pip install bencode.py
now the script does not complain

**Comment by ctminime** [comment]
I plan to make that clearer in the instructions that it is necessary. I now see that it gets lost in the rest of the instructions.
