### ISSUE TITLE
It works only if the torrents save paths was on single drive?

### ISSUE THREAD

**Issue by slrslr** [ctminime/QB_Migrate_to_Linux#2]
So if i had files spread across several drives (D: E: F:) and currently i have it on two Linux mount points /a /b
I can not use this script since it use only one root directory for all torrents?
linux_dir_start = "/newdir/"

i am finding the fastest way to add my Wind0ws t0rrents to Linux without need to recheck. I see the qbt has option to skip recheck when adding torrent. But still i would have to categorize/tag newly added torrents.

Can you allow user to do custom replacement of multiple paths?

**Comment by ctminime** [comment]
This script works on the "fastresume" files that are specific to QB not on the actual torrent files. All fastresume files should be in the same directory as defined by the QB installation. For example, in Windows, the default location for the fastresume file is c:\users\{username}\AppData\local\qBittorrent\BT_backup. Therefore, there should not be any reason to modify this for multiple source locations.

**Comment by slrslr** [comment]
I have not meant multiple paths for a fastresume files, but multiple qbittorrent save_paths that needs to be replaced.
Some people do not save data (lets say movies, OS images) into single location and so needs to do multiple paths replacement. Question was how to do it and if the tool allows that. It can be good if the tool guide user and for example preview the results so user know he will not damage the files and will see how the result will look like without the need to numerous times delete and restore BT_backup and multiple times star & quit qbittorrent to achieve wanted result.

Here is how i did multiple paths replacement using different tool (commands highlighted in a block of code):
https://github.com/rumanzo/qbtchangetracker/issues/9

**Comment by ctminime** [comment]
Oh right, duh. Don't know why that didn't occur to me. So, this essentially boils down to 2 feature requests.
1. Allow for multiple sources and destinations.
2. Give preview of changes before writing the files.

I certain that can be done, I just need to figure out how to do it.

**Comment by ctminime** [comment]
Version 2 coming soon!

**Comment by ctminime** [comment]
Well, this took me MUCH longer than it should have, but it is now done. It will now do multiple drives and give preview of changes.

**Comment by Jieoz** [comment]
There is no error displayed, after running and entering the address of the BT_backup folder located, yes, the program disappears and terminates.
